<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_apenasderrotas</name>
   <tag></tag>
   <elementGuidId>1e4edb0b-fb8c-4b15-98b4-19b840560e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select/option[@value=&quot;loss&quot;]&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
