<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>9b2f77c8-7119-4bf6-94d8-da2a134495b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type='password'].input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password']&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
