<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>cbf6a18c-d2ac-44e0-b02b-a936206e082e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type='email'].input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email']&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
