<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nickname</name>
   <tag></tag>
   <elementGuidId>f9425eec-f0ac-4dc9-89b5-2098eb08241b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//input[@id='email']&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nickname']&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
