<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dashboard</name>
   <tag></tag>
   <elementGuidId>7f3c0799-c323-4cda-811c-4059478f393c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@id='dashboard']</value>
      <webElementGuid>298432b2-393e-47b4-bd02-89d61c43017a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
